### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by codbid** [trpo2023/cw-iv-222_optimal-rate#3]
Подразумевается, что Makefile должен создавать статическую библиотеку, иметь цели clean для очистки артефактов сборки и clean_all для очистки артефактов сборки и удаления исполняемого файла

**Comment by codbid** [comment]
Добавил пустой Makefile, необходимо настроить его

**Comment by pomidor2000** [comment]
Настроил Makefile
Issue не закрываю, т. к. ещё придется вносить правки.

**Comment by pomidor2000** [comment]
Done
