### ISSUE TITLE
Develop the o_rate library for selecting the optimal rate

### ISSUE THREAD

**Issue by codbid** [trpo2023/cw-iv-222_optimal-rate#5]
Необходимо создать библиотеку, включающую две функции - get_expense_from_file для извлечения трат пользователя из файла и optimal_rate для подбора оптимального тарифа
Подразумевается работа с json

**Comment by sergeyzhelezkin** [comment]
Необходимо использовать библиотеку json-c для работы с json. Требуется изменить Makefile для компиляции проекта вместе с библиотекой и изменить build.yml

**Comment by codbid** [comment]
Добавил функцию get_expense_from_file, которая из json файла рассчитывает в двух режимах расходы пользователя.

**Comment by codbid** [comment]
Ошибка сборки после добавления функции find_optimal_rate

**Comment by codbid** [comment]
Done
