### ISSUE TITLE
Add json files

### ISSUE THREAD

**Issue by codbid** [trpo2023/cw-iv-222_optimal-rate#8]
Необходимо добавить два файла в папку thirdparty:
1. Файл, содержащий случайные данные о расходах минут, гигабайтов и смс тарифа за каждый месяц, минимум 12 месяцев.
2. Файл, содержащий перечень доступных тарифов (можно взять тарифы какого либо мобильного оператора)

**Comment by pomidor2000** [comment]
В качестве перечня тарифов добавил тарифные планы мегафона

**Comment by pomidor2000** [comment]
Done
